services:
  postgres:
    image: postgres:16-alpine
    container_name: dashly_postgres
    restart: always
    environment:
      POSTGRES_DB: dashly_db
      POSTGRES_USER: dashly_user
      POSTGRES_PASSWORD: dashly_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dashly-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d dashly_db -U dashly_user']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dashly_redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - dashly-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: dashly_mosquitto
    restart: always
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - dashly-network

networks:
  dashly-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
